### PR TITLE
fix: change logic for missing classes secret to log error instead of not creating pods

### LINKED ISSUE #12: When classes secret is not defined, just log it and fail silently
_Describe the issue here._

##### Relevant URLs
- _Provide relevant URLs_

### PR DESCRIPTION
**Pull request by wojciechka**
Closes #12

This changes how handling errors related to retrieving secret classes is handled to only log the error and not create sidecar instead of returning and error, as this prevents the pods to from being created at all.

- [x] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/telegraf-operator/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [x] Tests pass (no build errors)
- [x] Rebased/mergeable

### CODE REVIEW

File: handler.go [hunk 1]
```diff
@@ -78,31 +80,37 @@ func (a *podInjector) Handle(ctx context.Context, req admission.Request) admissi
...
 	}
-	secret, err := addSidecar(pod, pod.GetName(), req.Namespace, classData)
-	if err != nil {
-		return admission.Errored(http.StatusBadRequest, err)
-	}
-	if req.Operation == admv1.Create {
-		err = a.client.Create(ctx, secret)
+
+	classData, err := a.getClassData(pod)
+	if err == nil {
```
Comment (gitirabassi) [inline handler.go]: This wouldn't work because if err != nil, then you into the `else` statement, it logs the error but then continue without the right informations. I like to fail fast. I think the right approach if err != nil is from L81 (the skip function) because that's what we actually want to do

Comment (wojciechka) [reply handler.go]: You are right, I can just return empty `Allowed` response. Very good point.

FYI this worked and logged message correctly, but I agree, with the new approach I just pushed it is much cleaner.

File: handler.go [hunk 2]
```diff
@@ -76,22 +78,30 @@ func (a *podInjector) Handle(ctx context.Context, req admission.Request) admissi
...
 	if name == "" {
 		name = names.SimpleNameGenerator.GenerateName(pod.GetGenerateName())
 		pod.SetName(name)
 		handlerLog.Info("name: " + name + ",  pod_getname=" + pod.GetName())
 	}
+
+	classData, err := a.getClassData(pod)
+	if err != nil {
+		a.Logger.Info(fmt.Sprintf("unable to find class data: %v ; not adding sidecar container", err))
+		return admission.Allowed("telegraf-injector could not create sidecar container")
```
Comment (gitirabassi) [inline handler.go]:
```suggestion
		return admission.Allowed("telegraf-operator could not create sidecar container")
```

File: handler.go [hunk 3]
```diff
@@ -76,22 +78,30 @@ func (a *podInjector) Handle(ctx context.Context, req admission.Request) admissi
 		return admission.Errored(http.StatusBadRequest, err)
 	}
 	if skip(pod) {
+		a.Logger.Info("skipping pod as telegraf-injector should not handle it")
 		return admission.Allowed("telegraf-injector has no power over this pod")
```
Comment (gitirabassi) [inline handler.go]:
```suggestion
		return admission.Allowed("telegraf-operator has no power over this pod")
```

**Comment by wojciechka** [comment]
> Looks good! have you tried running this locally?

Yes I did, both with and without the secret present, to validate both use cases.
